# -*- coding: utf-8 -*-
"""Multiple Linear Regression

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12m74rPld40d8nitNnecmahPAkRveGSzF

Multiple Linear Regression
"""

import pandas as pd
import numpy as np
df = pd.read_csv("https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/main/housing_LR.csv")
df.head(10)

housing = df[df.district=='Чиланзарский']
housing.head()

"""#Train/Test split"""

from sklearn.model_selection import train_test_split
train_set, test_set, = train_test_split(housing, test_size=0.10, random_state=42)

"""#ML"""

from sklearn import linear_model
MLR_model = linear_model.LinearRegression()
# x_train = np.asanyarray(train_set[['rooms','size','level','max_levels']])
x_train = np.asanyarray(train_set[['size','max_levels']])
y_train = np.asanyarray(train_set[['price']])
MLR_model.fit (x_train, y_train)
# Koeffisientlar (theta1, theta2, ...)
print('Coefficients: ', MLR_model.coef_)
print('theta0:', MLR_model.intercept_)

# Commented out IPython magic to ensure Python compatibility.
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline
sns.pairplot(df[['rooms','size','level','max_levels','price']])
plt.show()

"""#Modelni Baholaymiz"""

# x_test = np.asanyarray(test_set[['rooms','size','level','max_levels']])
x_test = np.asanyarray(test_set[['size','max_levels']])
y_test = np.asanyarray(test_set[['price']])
y_predict = MLR_model.predict(x_test)

from sklearn.metrics import mean_absolute_error, mean_squared_error

MAE = mean_absolute_error(y_test, y_predict)
RMSE = np.sqrt(mean_squared_error(y_test, y_predict))
print(f"{MAE=}")
print(f"{RMSE=}")

